services:
  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: pg_tileserv
    environment:
      DATABASE_URL: postgresql://postgres:100599@host.docker.internal:5432/osm_india
    ports:
      - "7800:7800"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
